# Imports

In [1]:
import numpy as np

# Numpy NDArray

`numpy.ndarray` is the fundamental data structure of numpy. It is a multidimensional array of elements of the same type. It is a generic multidimensional container for homogeneous data. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In numpy dimensions are called axes. The number of axes is rank. The shape of an array is a tuple of integers giving the size of the array along each axis.

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


## Axes

In numpy, axes are ordered from 0 to n-1. The first axis is the first dimension of the array, the second axis is the second dimension, and so on.

In [4]:
three_d_array = np.random.randint(0, 10, (3, 4, 5))
three_d_array

array([[[4, 7, 0, 6, 8],
        [2, 3, 9, 1, 6],
        [7, 3, 8, 1, 3],
        [3, 8, 4, 9, 1]],

       [[3, 0, 2, 7, 9],
        [7, 9, 6, 3, 7],
        [7, 9, 8, 6, 6],
        [4, 8, 1, 7, 6]],

       [[9, 0, 8, 0, 7],
        [6, 1, 7, 3, 2],
        [0, 7, 4, 4, 7],
        [1, 0, 5, 5, 1]]])

Let's see the different axes of a 3D array:

In [10]:
three_d_array[0, :, :], three_d_array[0, :, :].shape

(array([[4, 7, 0, 6, 8],
        [2, 3, 9, 1, 6],
        [7, 3, 8, 1, 3],
        [3, 8, 4, 9, 1]]),
 (4, 5))

In [11]:
three_d_array[:, 0, :], three_d_array[:, 0, :].shape

(array([[4, 7, 0, 6, 8],
        [3, 0, 2, 7, 9],
        [9, 0, 8, 0, 7]]),
 (3, 5))

In [12]:
three_d_array[:, :, 0], three_d_array[:, :, 0].shape

(array([[4, 2, 7, 3],
        [3, 7, 7, 4],
        [9, 6, 0, 1]]),
 (3, 4))

This is easier to understand in 2D:

In [13]:
two_d_array = np.random.randint(0, 10, (3, 4))
two_d_array

array([[6, 8, 6, 2],
       [9, 8, 3, 9],
       [2, 6, 7, 1]])

In [14]:
two_d_array[0, :], two_d_array[0, :].shape

(array([6, 8, 6, 2]), (4,))

In [15]:
two_d_array[:, 0], two_d_array[:, 0].shape

(array([6, 9, 2]), (3,))

So, the first axis is the row axis and the second axis is the column axis.

In [16]:
np.sum(two_d_array, axis=0)

array([17, 22, 16, 12])

It seems that sum along the zeroth axis sums along columns and sum along the first axis sums along rows.

In [17]:
np.sum(two_d_array, axis=1)

array([22, 29, 16])

## Shape

Next, we will see the shape of a 3D array:

In [20]:
three_d_array = np.random.randint(0, 10, (3, 4, 5))
three_d_array

array([[[6, 1, 6, 0, 7],
        [8, 3, 4, 3, 1],
        [1, 5, 2, 7, 6],
        [5, 8, 0, 2, 4]],

       [[4, 4, 5, 2, 2],
        [0, 4, 7, 8, 7],
        [1, 9, 7, 0, 9],
        [0, 1, 3, 5, 9]],

       [[3, 0, 2, 1, 4],
        [0, 8, 5, 7, 1],
        [0, 0, 7, 4, 3],
        [6, 6, 6, 5, 3]]])

Again, it is easier to understand in 2D:

In [21]:
two_d_array = np.random.randint(0, 10, (3, 4))
two_d_array

array([[4, 2, 9, 6],
       [0, 2, 2, 5],
       [6, 7, 9, 3]])

So, the first element of the shape is the number of rows and the second element of the shape is the number of columns.

## Broadcasting

Broadcasting is a mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations.

There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape, as in the following example:

In [23]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:



In [24]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

The result is equivalent to the previous example where `b` was an array. We can think of the scalar `b` being stretched during the arithmetic operation into an array with the same shape as `a`.

![](https://numpy.org/doc/stable/_images/broadcasting_1.png)

### General Broadcasting Rules

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when

1. they are equal, or
2. one of them is 1

For example, if you have a `256x256x3` array of RGB values, and you want to scale each color in the image by a different value, you can multiply the image by a one-dimensional array with 3 values. Lining up the sizes of the trailing axes of these arrays according to the broadcast rules, shows that they are compatible.

 Note that missing dimensions are assumed to have size one.

In [36]:
image = np.random.randint(0, 256, (4, 4, 3))
scale = np.array([1, 0.5,0])
display(image)
display(scale)
display(image.shape, scale.shape)
gray_image = image*scale
# gray_image
gray_image.shape

array([[[236,  61,  67],
        [173,  16, 255],
        [ 57, 119, 112],
        [ 22, 139,  59]],

       [[  8, 182, 210],
        [201, 177,  20],
        [112,  88, 237],
        [118, 119, 138]],

       [[ 17,  54,  14],
        [124,  72, 179],
        [167,  25, 132],
        [  3, 165,   5]],

       [[ 45,  20,   3],
        [155, 168,  64],
        [ 98, 204, 178],
        [249,  41, 176]]])

array([1. , 0.5, 0. ])

(4, 4, 3)

(3,)

(4, 4, 3)

In the above problem, the shape `(3,)` is treated as `(1,3)`. We can see this:

In [38]:
image = np.random.randint(0, 256, (4, 4, 3))
scale = np.array([[1, 0.5,0]])
display(image.shape, scale.shape)
gray_image = image*scale
gray_image.shape

(4, 4, 3)

(1, 3)

(4, 4, 3)

In [41]:
image = np.random.randint(0, 256, (4, 4, 3))
scale = np.array([[1], [0.5], [0]])
display(image.shape, scale.shape)
try:
    gray_image = image*scale
    gray_image.shape
except Exception as e:
    print("Error Raised:")
    print(e)

(4, 4, 3)

(3, 1)

Error Raised:
operands could not be broadcast together with shapes (4,4,3) (3,1) 


We see that the shape is not `(3,1)` as that will give an error.

When either of the dimensions compared is one, the other is used. In other words, dimensions with size 1 are stretched or “copied” to match the other.

Another example is:
```python
A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5
```

A more involved example is:

<p>If <code class="docutils literal notranslate"><span class="pre">a.shape</span></code> is (5,1), <code class="docutils literal notranslate"><span class="pre">b.shape</span></code> is (1,6), <code class="docutils literal notranslate"><span class="pre">c.shape</span></code> is (6,)
and <code class="docutils literal notranslate"><span class="pre">d.shape</span></code> is () so that <em>d</em> is a scalar, then <em>a</em>, <em>b</em>, <em>c</em>,
and <em>d</em> are all broadcastable to dimension (5,6); and</p>

<ul class="simple">
<li><p><em>a</em> acts like a (5,6) array where <code class="docutils literal notranslate"><span class="pre">a[:,0]</span></code> is broadcast to the other
columns,</p></li>
<li><p><em>b</em> acts like a (5,6) array where <code class="docutils literal notranslate"><span class="pre">b[0,:]</span></code> is broadcast
to the other rows,</p></li>
<li><p><em>c</em> acts like a (1,6) array and therefore like a (5,6) array
where <code class="docutils literal notranslate"><span class="pre">c[:]</span></code> is broadcast to every row, and finally,</p></li>
<li><p><em>d</em> acts like a (5,6) array where the single value is repeated.</p></li>
</ul>

Here are some more examples:

```python
A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```

Here are examples of shapes that do not broadcast:

```python
A      (1d array):  3
B      (1d array):  4 # trailing dimensions do not match

A      (2d array):      2 x 1
B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched
```

![](https://numpy.org/doc/stable/_images/broadcasting_2.png)

A one dimensional array added to a two dimensional array results in broadcasting if number of 1-d array elements matches the number of 2-d array columns.

![](https://numpy.org/doc/stable/_images/broadcasting_3.png)

When the trailing dimensions of the arrays are unequal, broadcasting fails because it is impossible to align the values in the rows of the 1st array with the elements of the 2nd arrays for element-by-element addition.

![](https://numpy.org/doc/stable/_images/broadcasting_4.png)

In some cases, broadcasting stretches both arrays to form an output array larger than either of the initial arrays.



Broadcasting provides a convenient way of taking the outer product (or any other outer operation) of two arrays. The following example shows an outer addition operation of two 1-d arrays:

In [45]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

<p>Here the <code class="docutils literal notranslate"><span class="pre">newaxis</span></code> index operator inserts a new axis into <code class="docutils literal notranslate"><span class="pre">a</span></code>,
making it a two-dimensional <code class="docutils literal notranslate"><span class="pre">4x1</span></code> array.  Combining the <code class="docutils literal notranslate"><span class="pre">4x1</span></code> array
with <code class="docutils literal notranslate"><span class="pre">b</span></code>, which has shape <code class="docutils literal notranslate"><span class="pre">(3,)</span></code>, yields a <code class="docutils literal notranslate"><span class="pre">4x3</span></code> array.</p>

In [43]:
a.shape, a[:, np.newaxis].shape, b.shape

((4,), (4, 1), (3,))

In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(0, 100, (8,5,4,1))

In [5]:
arr1.shape

(8, 5, 4, 1)

In [8]:
arr2 = np.array([1,2,3,4,5])
arr2.shape

(5,)

In [7]:
arr = arr1+arr2
arr.shape

(8, 5, 4, 5)

In [9]:
arr3 = np.random.randint(0, 100, (4,6))

In [10]:
(arr1+arr3).shape

(8, 5, 4, 6)

In [11]:
(arr1*arr3).shape

(8, 5, 4, 6)

In [14]:
a=np.random.randint(0, 100, (3,3,3))
b=np.random.randint(0, 100, (3,3,3))
np.dot(a,b).shape

(3, 3, 3, 3)

In [16]:
a

array([[[87, 47, 78],
        [16, 11, 40],
        [62, 59, 62]],

       [[29, 83,  8],
        [93, 74,  0],
        [38, 51, 86]],

       [[65, 77, 67],
        [89, 30, 73],
        [ 1, 32, 20]]])

In [17]:
b

array([[[22, 60,  4],
        [85, 55, 54],
        [79, 49,  8]],

       [[73, 62, 70],
        [29, 89, 37],
        [10, 77, 35]],

       [[97, 96, 78],
        [38, 24, 99],
        [40, 55,  8]]])

In [18]:
np.dot(a,b)


array([[[[12071, 11627,  3510],
         [ 8494, 15583, 10559],
         [13345, 13770, 12063]],

        [[ 4447,  3525,   978],
         [ 1887,  5051,  2927],
         [ 3570,  4000,  2657]],

        [[11277, 10003,  3930],
         [ 6857, 13869,  8693],
         [10736, 10778, 11173]]],


       [[[ 8325,  6697,  4662],
         [ 4604,  9801,  5381],
         [ 6287,  5216, 10543]],

        [[ 8336,  9650,  4368],
         [ 8935, 12352,  9248],
         [11833, 10704, 14580]],

        [[11965,  9299,  3594],
         [ 5113, 13517,  7557],
         [ 9064,  9602,  8701]]],


       [[[13268, 11418,  4954],
         [ 7648, 16042,  9744],
         [11911, 11773, 13229]],

        [[10275, 10567,  2560],
         [ 8097, 13809,  9895],
         [12693, 13279, 10496]],

        [[ 4322,  2800,  1892],
         [ 1201,  4450,  1954],
         [ 2113,  1964,  3406]]]])

In [19]:
np.matmul(a,b)

array([[[12071, 11627,  3510],
        [ 4447,  3525,   978],
        [11277, 10003,  3930]],

       [[ 4604,  9801,  5381],
        [ 8935, 12352,  9248],
        [ 5113, 13517,  7557]],

       [[11911, 11773, 13229],
        [12693, 13279, 10496],
        [ 2113,  1964,  3406]]])